/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Test2RouteImport } from './routes/test-2'
import { Route as ScandiRouteImport } from './routes/scandi'
import { Route as MynuoraRouteImport } from './routes/mynuora'
import { Route as IndexRouteImport } from './routes/index'

const Test2Route = Test2RouteImport.update({
  id: '/test-2',
  path: '/test-2',
  getParentRoute: () => rootRouteImport,
} as any)
const ScandiRoute = ScandiRouteImport.update({
  id: '/scandi',
  path: '/scandi',
  getParentRoute: () => rootRouteImport,
} as any)
const MynuoraRoute = MynuoraRouteImport.update({
  id: '/mynuora',
  path: '/mynuora',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mynuora': typeof MynuoraRoute
  '/scandi': typeof ScandiRoute
  '/test-2': typeof Test2Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mynuora': typeof MynuoraRoute
  '/scandi': typeof ScandiRoute
  '/test-2': typeof Test2Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mynuora': typeof MynuoraRoute
  '/scandi': typeof ScandiRoute
  '/test-2': typeof Test2Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/mynuora' | '/scandi' | '/test-2'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/mynuora' | '/scandi' | '/test-2'
  id: '__root__' | '/' | '/mynuora' | '/scandi' | '/test-2'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MynuoraRoute: typeof MynuoraRoute
  ScandiRoute: typeof ScandiRoute
  Test2Route: typeof Test2Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test-2': {
      id: '/test-2'
      path: '/test-2'
      fullPath: '/test-2'
      preLoaderRoute: typeof Test2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scandi': {
      id: '/scandi'
      path: '/scandi'
      fullPath: '/scandi'
      preLoaderRoute: typeof ScandiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mynuora': {
      id: '/mynuora'
      path: '/mynuora'
      fullPath: '/mynuora'
      preLoaderRoute: typeof MynuoraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MynuoraRoute: MynuoraRoute,
  ScandiRoute: ScandiRoute,
  Test2Route: Test2Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
